[tool.poetry]
name = "answerbook-api"
version = "0.1.0"
description = ""
authors = ["Ivan Procaccini <ivanprocaccini905@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
pytest = "^8.2.1"
pytest-factoryboy = "^2.7.0"
pytest-cov = "^5.0.0"
typer = "^0.12.3"
freezegun = "^1.5.1"
pydantic-settings = "^2.2.1"
psycopg2 = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
